# Generated by Django 5.2.8 on 2025-11-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(upload_to='galeria/%Y/%m/%d/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Imagens da Galeria',
                'ordering': ['-data_upload'],
            },
        ),
    ]
