# Generated by Django 5.2.8 on 2025-12-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemgaleria',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='imagemgaleria',
            name='imagem',
            field=models.ImageField(upload_to='galeria/'),
        ),
    ]
