# Generated by Django 5.2.8 on 2025-12-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_core', '0002_remove_imagemgaleria_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_evento', models.DateField(help_text='Data em que a foto/vídeo foi feito.', verbose_name='Data do Evento')),
                ('imagem', models.ImageField(blank=True, help_text='Obrigatório se URL do Vídeo estiver vazio.', null=True, upload_to='galeria/')),
                ('url_video', models.URLField(blank=True, help_text='Obrigatório se Imagem estiver vazio. Use links de EMBED (iframe) do YouTube ou outra plataforma.', max_length=500, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item da Galeria (Foto/Vídeo)',
                'verbose_name_plural': 'Itens da Galeria',
                'ordering': ['-data_evento', '-data_upload'],
            },
        ),
        migrations.DeleteModel(
            name='ImagemGaleria',
        ),
    ]
