# Generated by Django 5.2.8 on 2025-12-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_core', '0003_mediagaleria_delete_imagemgaleria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediagaleria',
            name='imagem',
            field=models.FileField(blank=True, help_text='Obrigatório se URL do Vídeo estiver vazio.', null=True, upload_to='galeria/'),
        ),
    ]
