# Generated by Django 5.2.8 on 2025-12-01 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_core', '0004_alter_mediagaleria_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediagaleria',
            name='imagem',
            field=models.FileField(blank=True, help_text='Faça upload de uma imagem (JPG, PNG) ou um vídeo (MP4, MOV, WEBM).', null=True, upload_to='galeria/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'webm'])], verbose_name='Foto ou Vídeo (Upload Direto)'),
        ),
        migrations.AlterField(
            model_name='mediagaleria',
            name='url_video',
            field=models.URLField(blank=True, help_text="Opcional: Use o link de EMBED (iframe) do YouTube ou outra plataforma. Preenchido, ignora o campo 'Foto ou Vídeo'.", max_length=500, null=True, verbose_name='URL de Embed (YouTube/Vimeo)'),
        ),
    ]
