# Generated by Django 5.2.8 on 2025-12-01 03:40

import ct_core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_core', '0005_alter_mediagaleria_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediagaleria',
            name='imagem',
            field=models.FileField(blank=True, help_text='Faça upload de uma imagem (JPG, PNG) ou um vídeo (MP4, MOV, WEBM).', null=True, upload_to=ct_core.models.galeria_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'webm'])], verbose_name='Foto ou Vídeo (Upload Direto)'),
        ),
    ]
